//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;
var Int64 = require('node-int64');


var ttypes = module.exports = {};
ttypes.SyncReason = {
  'UNSPECIFIED' : 0,
  'UNKNOWN' : 1,
  'INITIALIZATION' : 2,
  'OPERATION' : 3,
  'FULL_SYNC' : 4,
  'AUTO_REPAIR' : 5,
  'MANUAL_REPAIR' : 6,
  'INTERNAL' : 7
};
ttypes.MidType = {
  'USER' : 0,
  'ROOM' : 1,
  'GROUP' : 2,
  'SQUARE' : 3,
  'SQUARE_CHAT' : 4,
  'SQUARE_MEMBER' : 5,
  'BOT' : 6
};
ttypes.TalkExceptionCode = {
  'ILLEGAL_ARGUMENT' : 0,
  'AUTHENTICATION_FAILED' : 1,
  'DB_FAILED' : 2,
  'INVALID_STATE' : 3,
  'EXCESSIVE_ACCESS' : 4,
  'NOT_FOUND' : 5,
  'INVALID_LENGTH' : 6,
  'NOT_AVAILABLE_USER' : 7,
  'NOT_AUTHORIZED_DEVICE' : 8,
  'INVALID_MID' : 9,
  'NOT_A_MEMBER' : 10,
  'INCOMPATIBLE_APP_VERSION' : 11,
  'NOT_READY' : 12,
  'NOT_AVAILABLE_SESSION' : 13,
  'NOT_AUTHORIZED_SESSION' : 14,
  'SYSTEM_ERROR' : 15,
  'NO_AVAILABLE_VERIFICATION_METHOD' : 16,
  'NOT_AUTHENTICATED' : 17,
  'INVALID_IDENTITY_CREDENTIAL' : 18,
  'NOT_AVAILABLE_IDENTITY_IDENTIFIER' : 19,
  'INTERNAL_ERROR' : 20,
  'NO_SUCH_IDENTITY_IDENFIER' : 21,
  'DEACTIVATED_ACCOUNT_BOUND_TO_THIS_IDENTITY' : 22,
  'ILLEGAL_IDENTITY_CREDENTIAL' : 23,
  'UNKNOWN_CHANNEL' : 24,
  'NO_SUCH_MESSAGE_BOX' : 25,
  'NOT_AVAILABLE_MESSAGE_BOX' : 26,
  'CHANNEL_DOES_NOT_MATCH' : 27,
  'NOT_YOUR_MESSAGE' : 28,
  'MESSAGE_DEFINED_ERROR' : 29,
  'USER_CANNOT_ACCEPT_PRESENTS' : 30,
  'USER_NOT_STICKER_OWNER' : 32,
  'MAINTENANCE_ERROR' : 33,
  'ACCOUNT_NOT_MATCHED' : 34,
  'ABUSE_BLOCK' : 35,
  'NOT_FRIEND' : 36,
  'NOT_ALLOWED_CALL' : 37,
  'BLOCK_FRIEND' : 38,
  'INCOMPATIBLE_VOIP_VERSION' : 39,
  'INVALID_SNS_ACCESS_TOKEN' : 40,
  'EXTERNAL_SERVICE_NOT_AVAILABLE' : 41,
  'NOT_ALLOWED_ADD_CONTACT' : 42,
  'NOT_CERTIFICATED' : 43,
  'NOT_ALLOWED_SECONDARY_DEVICE' : 44,
  'INVALID_PIN_CODE' : 45,
  'NOT_FOUND_IDENTITY_CREDENTIAL' : 46,
  'EXCEED_FILE_MAX_SIZE' : 47,
  'EXCEED_DAILY_QUOTA' : 48,
  'NOT_SUPPORT_SEND_FILE' : 49,
  'MUST_UPGRADE' : 50,
  'NOT_AVAILABLE_PIN_CODE_SESSION' : 51,
  'EXPIRED_REVISION' : 52,
  'NOT_YET_PHONE_NUMBER' : 54,
  'BAD_CALL_NUMBER' : 55,
  'UNAVAILABLE_CALL_NUMBER' : 56,
  'NOT_SUPPORT_CALL_SERVICE' : 57,
  'CONGESTION_CONTROL' : 58,
  'NO_BALANCE' : 59,
  'NOT_PERMITTED_CALLER_ID' : 60,
  'NO_CALLER_ID_LIMIT_EXCEEDED' : 61,
  'CALLER_ID_VERIFICATION_REQUIRED' : 62,
  'NO_CALLER_ID_LIMIT_EXCEEDED_AND_VERIFICATION_REQUIRED' : 63,
  'MESSAGE_NOT_FOUND' : 64,
  'INVALID_ACCOUNT_MIGRATION_PINCODE_FORMAT' : 65,
  'ACCOUNT_MIGRATION_PINCODE_NOT_MATCHED' : 66,
  'ACCOUNT_MIGRATION_PINCODE_BLOCKED' : 67,
  'INVALID_PASSWORD_FORMAT' : 69,
  'FEATURE_RESTRICTED' : 70,
  'MESSAGE_NOT_DESTRUCTIBLE' : 71,
  'PAID_CALL_REDEEM_FAILED' : 72,
  'PREVENTED_JOIN_BY_TICKET' : 73,
  'SEND_MESSAGE_NOT_PERMITTED_FROM_LINE_AT' : 75,
  'SEND_MESSAGE_NOT_PERMITTED_WHILE_AUTO_REPLY' : 76,
  'SECURITY_CENTER_NOT_VERIFIED' : 77,
  'SECURITY_CENTER_BLOCKED_BY_SETTING' : 78,
  'SECURITY_CENTER_BLOCKED' : 79,
  'TALK_PROXY_EXCEPTION' : 80,
  'E2EE_INVALID_PROTOCOL' : 81,
  'E2EE_RETRY_ENCRYPT' : 82,
  'E2EE_UPDATE_SENDER_KEY' : 83,
  'E2EE_UPDATE_RECEIVER_KEY' : 84,
  'E2EE_INVALID_ARGUMENT' : 85,
  'E2EE_INVALID_VERSION' : 86,
  'E2EE_SENDER_DISABLED' : 87,
  'E2EE_RECEIVER_DISABLED' : 88,
  'E2EE_SENDER_NOT_ALLOWED' : 89,
  'E2EE_RECEIVER_NOT_ALLOWED' : 90,
  'E2EE_RESEND_FAIL' : 91,
  'E2EE_RESEND_OK' : 92,
  'HITOKOTO_BACKUP_NO_AVAILABLE_DATA' : 93,
  'E2EE_UPDATE_PRIMARY_DEVICE' : 94,
  'SUCCESS' : 95,
  'CANCEL' : 96,
  'E2EE_PRIMARY_NOT_SUPPORT' : 97,
  'E2EE_RETRY_PLAIN' : 98,
  'E2EE_RECREATE_GROUP_KEY' : 99,
  'E2EE_GROUP_TOO_MANY_MEMBERS' : 100,
  'SERVER_BUSY' : 101,
  'NOT_ALLOWED_ADD_FOLLOW' : 102,
  'INCOMING_FRIEND_REQUEST_LIMIT' : 103,
  'OUTGOING_FRIEND_REQUEST_LIMIT' : 104,
  'OUTGOING_FRIEND_REQUEST_QUOTA' : 105,
  'DUPLICATED' : 106,
  'BANNED' : 107,
  'NOT_AN_INVITEE' : 108,
  'NOT_AN_OUTSIDER' : 109,
  'EMPTY_GROUP' : 111,
  'EXCEED_FOLLOW_LIMIT' : 112,
  'UNSUPPORTED_ACCOUNT_TYPE' : 113,
  'AGREEMENT_REQUIRED' : 114
};
ttypes.C59756ii = {
  'NOTIFICATION_ENABLE' : 0,
  'NOTIFICATION_MUTE_EXPIRATION' : 1,
  'NOTIFICATION_NEW_MESSAGE' : 2,
  'NOTIFICATION_GROUP_INVITATION' : 3,
  'NOTIFICATION_SHOW_MESSAGE' : 4,
  'NOTIFICATION_INCOMING_CALL' : 5,
  'PRIVACY_SYNC_CONTACTS' : 6,
  'PRIVACY_SEARCH_BY_PHONE_NUMBER' : 7,
  'NOTIFICATION_SOUND_MESSAGE' : 8,
  'NOTIFICATION_SOUND_GROUP' : 9,
  'CONTACT_MY_TICKET' : 10,
  'IDENTITY_PROVIDER' : 11,
  'IDENTITY_IDENTIFIER' : 12,
  'PRIVACY_SEARCH_BY_USERID' : 13,
  'PRIVACY_SEARCH_BY_EMAIL' : 14,
  'PREFERENCE_LOCALE' : 15,
  'NOTIFICATION_DISABLED_WITH_SUB' : 16,
  'NOTIFICATION_PAYMENT' : 17,
  'SECURITY_CENTER_SETTINGS' : 18,
  'SNS_ACCOUNT' : 19,
  'PHONE_REGISTRATION' : 20,
  'PRIVACY_ALLOW_SECONDARY_DEVICE_LOGIN' : 21,
  'CUSTOM_MODE' : 22,
  'PRIVACY_PROFILE_IMAGE_POST_TO_MYHOME' : 23,
  'EMAIL_CONFIRMATION_STATUS' : 24,
  'PRIVACY_RECV_MESSAGES_FROM_NOT_FRIEND' : 25,
  'PRIVACY_AGREE_USE_LINECOIN_TO_PAIDCALL' : 26,
  'PRIVACY_AGREE_USE_PAIDCALL' : 27,
  'ACCOUNT_MIGRATION_PINCODE' : 28,
  'ENFORCED_INPUT_ACCOUNT_MIGRATION_PINCODE' : 29,
  'PRIVACY_ALLOW_FRIEND_REQUEST' : 30,
  'E2EE_ENABLE' : 33,
  'HITOKOTO_BACKUP_REQUESTED' : 34,
  'PRIVACY_PROFILE_MUSIC_POST_TO_MYHOME' : 35,
  'CONTACT_ALLOW_FOLLOWING' : 36,
  'PRIVACY_ALLOW_NEARBY' : 37,
  'AGREEMENT_NEARBY' : 38,
  'AGREEMENT_SQUARE' : 39,
  'NOTIFICATION_MENTION' : 40,
  'ALLOW_UNREGISTRATION_SECONDARY_DEVICE' : 41,
  'AGREEMENT_BOT_USE' : 42,
  'AGREEMENT_SHAKE_FUNCTION' : 43,
  'AGREEMENT_MOBILE_CONTACT_NAME' : 44,
  'NOTIFICATION_THUMBNAIL' : 45,
  'AGREEMENT_SOUND_TO_TEXT' : 46,
  'AGREEMENT_PRIVACY_POLICY_VERSION' : 47,
  'AGREEMENT_AD_BY_WEB_ACCESS' : 48,
  'AGREEMENT_PHONE_NUMBER_MATCHING' : 49,
  'AGREEMENT_COMMUNICATION_INFO' : 50,
  'PRIVACY_SHARE_PERSONAL_INFO_TO_FRIENDS' : 51,
  'AGREEMENT_THINGS_WIRELESS_COMMUNICATION' : 52,
  'AGREEMENT_GDPR' : 53,
  'PRIVACY_STATUS_MESSAGE_HISTORY' : 54,
  'AGREEMENT_PROVIDE_LOCATION' : 55,
  'AGREEMENT_BEACON' : 56,
  'PRIVACY_PROFILE_HISTORY' : 57,
  'AGREEMENT_CONTENTS_SUGGEST' : 58,
  'AGREEMENT_CONTENTS_SUGGEST_DATA_COLLECTION' : 59,
  'PRIVACY_AGE_RESULT' : 60,
  'PRIVACY_AGE_RESULT_RECEIVED' : 61,
  'AGREEMENT_OCR_IMAGE_COLLECTION' : 62,
  'PRIVACY_ALLOW_FOLLOW' : 63,
  'PRIVACY_SHOW_FOLLOW_LIST' : 64,
  'NOTIFICATION_BADGE_TALK_ONLY' : 65
};
ttypes.UpdatedAttribute = {
  'NAME' : 1,
  'PICTURE_STATUS' : 2,
  'PREVENTED_JOIN_BY_TICKET' : 4,
  'NOTIFICATION_SETTING' : 8,
  'INVITATION_TICKET' : 16,
  'FAVORITE_TIMESTAMP' : 32,
  'CHAT_TYPE' : 64
};
ttypes.UpdateExtendedProfileAttributeAttr = {
  'BIRTHDAY' : 0
};
ttypes.ChatType = {
  'GROUP' : 0,
  'ROOM' : 1,
  'PEER' : 2
};
ttypes.C58964da = {
  'BACKGROUND' : 0,
  'KEYWORD' : 1
};
ttypes.C59265fa = {
  'LOW' : 0
};
ttypes.YearPrivacyLevelType = {
  'PUBLIC' : 0,
  'PRIVATE' : 1
};
var TalkException = module.exports.TalkException = function(args) {
  Thrift.TException.call(this, "TalkException");
  this.name = "TalkException";
  this.code = null;
  this.reason = null;
  this.parameterMap = null;
  if (args) {
    if (args.code !== undefined && args.code !== null) {
      this.code = args.code;
    }
    if (args.reason !== undefined && args.reason !== null) {
      this.reason = args.reason;
    }
    if (args.parameterMap !== undefined && args.parameterMap !== null) {
      this.parameterMap = Thrift.copyMap(args.parameterMap, [null]);
    }
  }
};
Thrift.inherits(TalkException, Thrift.TException);
TalkException.prototype.name = 'TalkException';
TalkException.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.code = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.reason = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.MAP) {
        this.parameterMap = {};
        var _rtmp31 = input.readMapBegin();
        var _size0 = _rtmp31.size || 0;
        for (var _i2 = 0; _i2 < _size0; ++_i2) {
          var key3 = null;
          var val4 = null;
          key3 = input.readString();
          val4 = input.readString();
          this.parameterMap[key3] = val4;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TalkException.prototype.write = function(output) {
  output.writeStructBegin('TalkException');
  if (this.code !== null && this.code !== undefined) {
    output.writeFieldBegin('code', Thrift.Type.I32, 1);
    output.writeI32(this.code);
    output.writeFieldEnd();
  }
  if (this.reason !== null && this.reason !== undefined) {
    output.writeFieldBegin('reason', Thrift.Type.STRING, 2);
    output.writeString(this.reason);
    output.writeFieldEnd();
  }
  if (this.parameterMap !== null && this.parameterMap !== undefined) {
    output.writeFieldBegin('parameterMap', Thrift.Type.MAP, 3);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.parameterMap));
    for (var kiter5 in this.parameterMap) {
      if (this.parameterMap.hasOwnProperty(kiter5)) {
        var viter6 = this.parameterMap[kiter5];
        output.writeString(kiter5);
        output.writeString(viter6);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AcceptChatInvitationByTicketResponse = module.exports.AcceptChatInvitationByTicketResponse = function(args) {
};
AcceptChatInvitationByTicketResponse.prototype = {};
AcceptChatInvitationByTicketResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AcceptChatInvitationByTicketResponse.prototype.write = function(output) {
  output.writeStructBegin('AcceptChatInvitationByTicketResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CancelChatInvitationResponse = module.exports.CancelChatInvitationResponse = function(args) {
};
CancelChatInvitationResponse.prototype = {};
CancelChatInvitationResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CancelChatInvitationResponse.prototype.write = function(output) {
  output.writeStructBegin('CancelChatInvitationResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CreateChatResponse = module.exports.CreateChatResponse = function(args) {
  this.chat = null;
  if (args) {
    if (args.chat !== undefined && args.chat !== null) {
      this.chat = new ttypes.Chat(args.chat);
    }
  }
};
CreateChatResponse.prototype = {};
CreateChatResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.chat = new ttypes.Chat();
        this.chat.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreateChatResponse.prototype.write = function(output) {
  output.writeStructBegin('CreateChatResponse');
  if (this.chat !== null && this.chat !== undefined) {
    output.writeFieldBegin('chat', Thrift.Type.STRUCT, 1);
    this.chat.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DeleteOtherFromChatResponse = module.exports.DeleteOtherFromChatResponse = function(args) {
};
DeleteOtherFromChatResponse.prototype = {};
DeleteOtherFromChatResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DeleteOtherFromChatResponse.prototype.write = function(output) {
  output.writeStructBegin('DeleteOtherFromChatResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DeleteSelfFromChatResponse = module.exports.DeleteSelfFromChatResponse = function(args) {
};
DeleteSelfFromChatResponse.prototype = {};
DeleteSelfFromChatResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DeleteSelfFromChatResponse.prototype.write = function(output) {
  output.writeStructBegin('DeleteSelfFromChatResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Message = module.exports.Message = function(args) {
  this._from = null;
  this.displayName = null;
  this.picturePath = null;
  this.type = null;
  this.person = null;
  this.person2 = null;
  this.personName = null;
  this.personName2 = null;
  this.to = null;
  this.toType = null;
  this.id = null;
  this.createdTime = null;
  this.deliveredTime = null;
  this.text = null;
  this.location = null;
  this.hasContent = null;
  this.contentType = null;
  this.contentPreview = null;
  this.contentMetadata = null;
  this.sessionId = null;
  this.chunks = null;
  this.relatedMessageId = null;
  this.messageRelationType = null;
  this.readCount = null;
  this.relatedMessageServiceCode = null;
  if (args) {
    if (args._from !== undefined && args._from !== null) {
      this._from = args._from;
    }
    if (args.displayName !== undefined && args.displayName !== null) {
      this.displayName = args.displayName;
    }
    if (args.picturePath !== undefined && args.picturePath !== null) {
      this.picturePath = args.picturePath;
    }
    if (args.type !== undefined && args.type !== null) {
      this.type = args.type;
    }
    if (args.person !== undefined && args.person !== null) {
      this.person = args.person;
    }
    if (args.person2 !== undefined && args.person2 !== null) {
      this.person2 = args.person2;
    }
    if (args.personName !== undefined && args.personName !== null) {
      this.personName = args.personName;
    }
    if (args.personName2 !== undefined && args.personName2 !== null) {
      this.personName2 = args.personName2;
    }
    if (args.to !== undefined && args.to !== null) {
      this.to = args.to;
    }
    if (args.toType !== undefined && args.toType !== null) {
      this.toType = args.toType;
    }
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.createdTime !== undefined && args.createdTime !== null) {
      this.createdTime = args.createdTime;
    }
    if (args.deliveredTime !== undefined && args.deliveredTime !== null) {
      this.deliveredTime = args.deliveredTime;
    }
    if (args.text !== undefined && args.text !== null) {
      this.text = args.text;
    }
    if (args.location !== undefined && args.location !== null) {
      this.location = new ttypes.Location(args.location);
    }
    if (args.hasContent !== undefined && args.hasContent !== null) {
      this.hasContent = args.hasContent;
    }
    if (args.contentType !== undefined && args.contentType !== null) {
      this.contentType = args.contentType;
    }
    if (args.contentPreview !== undefined && args.contentPreview !== null) {
      this.contentPreview = args.contentPreview;
    }
    if (args.contentMetadata !== undefined && args.contentMetadata !== null) {
      this.contentMetadata = Thrift.copyMap(args.contentMetadata, [null]);
    }
    if (args.sessionId !== undefined && args.sessionId !== null) {
      this.sessionId = args.sessionId;
    }
    if (args.chunks !== undefined && args.chunks !== null) {
      this.chunks = Thrift.copyList(args.chunks, [null]);
    }
    if (args.relatedMessageId !== undefined && args.relatedMessageId !== null) {
      this.relatedMessageId = args.relatedMessageId;
    }
    if (args.messageRelationType !== undefined && args.messageRelationType !== null) {
      this.messageRelationType = args.messageRelationType;
    }
    if (args.readCount !== undefined && args.readCount !== null) {
      this.readCount = args.readCount;
    }
    if (args.relatedMessageServiceCode !== undefined && args.relatedMessageServiceCode !== null) {
      this.relatedMessageServiceCode = args.relatedMessageServiceCode;
    }
  }
};
Message.prototype = {};
Message.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this._from = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 99:
      if (ftype == Thrift.Type.STRING) {
        this.displayName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 98:
      if (ftype == Thrift.Type.STRING) {
        this.picturePath = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 97:
      if (ftype == Thrift.Type.STRING) {
        this.type = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 96:
      if (ftype == Thrift.Type.STRING) {
        this.person = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 95:
      if (ftype == Thrift.Type.STRING) {
        this.person2 = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 94:
      if (ftype == Thrift.Type.STRING) {
        this.personName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 93:
      if (ftype == Thrift.Type.STRING) {
        this.personName2 = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.to = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.toType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I64) {
        this.createdTime = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I64) {
        this.deliveredTime = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.STRING) {
        this.text = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 11:
      if (ftype == Thrift.Type.STRUCT) {
        this.location = new ttypes.Location();
        this.location.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 14:
      if (ftype == Thrift.Type.BOOL) {
        this.hasContent = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 15:
      if (ftype == Thrift.Type.I32) {
        this.contentType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 17:
      if (ftype == Thrift.Type.STRING) {
        this.contentPreview = input.readBinary();
      } else {
        input.skip(ftype);
      }
      break;
      case 18:
      if (ftype == Thrift.Type.MAP) {
        var _size314 = 0;
        var _rtmp3318;
        this.contentMetadata = {};
        var _ktype315 = 0;
        var _vtype316 = 0;
        _rtmp3318 = input.readMapBegin();
        _ktype315 = _rtmp3318.ktype;
        _vtype316 = _rtmp3318.vtype;
        _size314 = _rtmp3318.size;
        for (var _i319 = 0; _i319 < _size314; ++_i319)
        {
          var key320 = null;
          var val321 = null;
          key320 = input.readString();
          val321 = input.readString();
          this.contentMetadata[key320] = val321;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 19:
      if (ftype == Thrift.Type.BYTE) {
        this.sessionId = input.readByte();
      } else {
        input.skip(ftype);
      }
      break;
      case 20:
      if (ftype == Thrift.Type.LIST) {
        var _size322 = 0;
        var _rtmp3326;
        this.chunks = [];
        var _etype325 = 0;
        _rtmp3326 = input.readListBegin();
        _etype325 = _rtmp3326.etype;
        _size322 = _rtmp3326.size;
        for (var _i327 = 0; _i327 < _size322; ++_i327)
        {
          var elem328 = null;
          elem328 = input.readBinary();
          this.chunks.push(elem328);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 21:
      if (ftype == Thrift.Type.STRING) {
        this.relatedMessageId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 22:
      if (ftype == Thrift.Type.I32) {
        this.messageRelationType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 23:
      if (ftype == Thrift.Type.I64) {
        this.readCount = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 24:
      if (ftype == Thrift.Type.I32) {
        this.relatedMessageServiceCode = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Message.prototype.write = function(output) {
  output.writeStructBegin('Message');
  if (this._from !== null && this._from !== undefined) {
    output.writeFieldBegin('_from', Thrift.Type.STRING, 1);
    output.writeString(this._from);
    output.writeFieldEnd();
  }
  if (this.to !== null && this.to !== undefined) {
    output.writeFieldBegin('to', Thrift.Type.STRING, 2);
    output.writeString(this.to);
    output.writeFieldEnd();
  }
  if (this.toType !== null && this.toType !== undefined) {
    output.writeFieldBegin('toType', Thrift.Type.I32, 3);
    output.writeI32(this.toType);
    output.writeFieldEnd();
  }
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 4);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.createdTime !== null && this.createdTime !== undefined) {
    output.writeFieldBegin('createdTime', Thrift.Type.I64, 5);
    output.writeI64(this.createdTime);
    output.writeFieldEnd();
  }
  if (this.deliveredTime !== null && this.deliveredTime !== undefined) {
    output.writeFieldBegin('deliveredTime', Thrift.Type.I64, 6);
    output.writeI64(this.deliveredTime);
    output.writeFieldEnd();
  }
  if (this.text !== null && this.text !== undefined) {
    output.writeFieldBegin('text', Thrift.Type.STRING, 10);
    output.writeString(this.text);
    output.writeFieldEnd();
  }
  if (this.location !== null && this.location !== undefined) {
    output.writeFieldBegin('location', Thrift.Type.STRUCT, 11);
    this.location.write(output);
    output.writeFieldEnd();
  }
  if (this.hasContent !== null && this.hasContent !== undefined) {
    output.writeFieldBegin('hasContent', Thrift.Type.BOOL, 14);
    output.writeBool(this.hasContent);
    output.writeFieldEnd();
  }
  if (this.contentType !== null && this.contentType !== undefined) {
    output.writeFieldBegin('contentType', Thrift.Type.I32, 15);
    output.writeI32(this.contentType);
    output.writeFieldEnd();
  }
  if (this.contentMetadata !== null && this.contentMetadata !== undefined) {
    output.writeFieldBegin('contentMetadata', Thrift.Type.MAP, 18);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(this.contentMetadata));
    for (var kiter75 in this.contentMetadata) {
      if (this.contentMetadata.hasOwnProperty(kiter75)) {
        var viter76 = this.contentMetadata[kiter75];
        output.writeString(kiter75);
        output.writeString(viter76);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.contentPreview !== null && this.contentPreview !== undefined) {
    output.writeFieldBegin('contentPreview', Thrift.Type.STRING, 17);
    output.writeBinary(this.contentPreview);
    output.writeFieldEnd();
  }
  if (this.sessionId !== null && this.sessionId !== undefined) {
    output.writeFieldBegin('sessionId', Thrift.Type.I64, 19);
    output.writeI64(this.sessionId);
    output.writeFieldEnd();
  }
  if (this.chunks !== null && this.chunks !== undefined) {
    output.writeFieldBegin('chunks', Thrift.Type.LIST, 20);
    output.writeListBegin(Thrift.Type.STRING, this.chunks.length);
    for (var iter77 in this.chunks) {
      if (this.chunks.hasOwnProperty(iter77)) {
        iter77 = this.chunks[iter77];
        output.writeBinary(iter77);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.relatedMessageId !== null && this.relatedMessageId !== undefined) {
    output.writeFieldBegin('relatedMessageId', Thrift.Type.STRING, 21);
    output.writeString(this.relatedMessageId);
    output.writeFieldEnd();
  }
  if (this.messageRelationType !== null && this.messageRelationType !== undefined) {
    output.writeFieldBegin('messageRelationType', Thrift.Type.I32, 22);
    output.writeI32(this.messageRelationType);
    output.writeFieldEnd();
  }
  if (this.readCount !== null && this.readCount !== undefined) {
    output.writeFieldBegin('readCount', Thrift.Type.I32, 23);
    output.writeI32(this.readCount);
    output.writeFieldEnd();
  }
  if (this.relatedMessageServiceCode !== null && this.relatedMessageServiceCode !== undefined) {
    output.writeFieldBegin('relatedMessageServiceCode', Thrift.Type.I32, 24);
    output.writeI32(this.relatedMessageServiceCode);
    output.writeFieldEnd();
  }
  if (this.appExtensionType !== null && this.appExtensionType !== undefined) {
    output.writeFieldBegin('appExtensionType', Thrift.Type.I32, 25);
    output.writeI32(this.appExtensionType);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var FindChatByTicketResponse = module.exports.FindChatByTicketResponse = function(args) {
  this.chat = null;
  if (args) {
    if (args.chat !== undefined && args.chat !== null) {
      this.chat = new ttypes.Chat(args.chat);
    }
  }
};
FindChatByTicketResponse.prototype = {};
FindChatByTicketResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.chat = new ttypes.Chat();
        this.chat.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FindChatByTicketResponse.prototype.write = function(output) {
  output.writeStructBegin('FindChatByTicketResponse');
  if (this.chat !== null && this.chat !== undefined) {
    output.writeFieldBegin('chat', Thrift.Type.STRUCT, 1);
    this.chat.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InviteIntoChatResponse = module.exports.InviteIntoChatResponse = function(args) {
};
InviteIntoChatResponse.prototype = {};
InviteIntoChatResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InviteIntoChatResponse.prototype.write = function(output) {
  output.writeStructBegin('InviteIntoChatResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ReissueChatTicketResponse = module.exports.ReissueChatTicketResponse = function(args) {
  this.ticketId = null;
  if (args) {
    if (args.ticketId !== undefined && args.ticketId !== null) {
      this.ticketId = args.ticketId;
    }
  }
};
ReissueChatTicketResponse.prototype = {};
ReissueChatTicketResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.ticketId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ReissueChatTicketResponse.prototype.write = function(output) {
  output.writeStructBegin('ReissueChatTicketResponse');
  if (this.ticketId !== null && this.ticketId !== undefined) {
    output.writeFieldBegin('ticketId', Thrift.Type.STRING, 1);
    output.writeString(this.ticketId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GetChatsResponse = module.exports.GetChatsResponse = function(args) {
  this.chats = null;
  if (args) {
    if (args.chats !== undefined && args.chats !== null) {
      this.chats = Thrift.copyList(args.chats, [null]);
    }
  }
};
GetChatsResponse.prototype = {};
GetChatsResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        this.chats = [];
        var _rtmp38 = input.readListBegin();
        var _size7 = _rtmp38.size || 0;
        for (var _i9 = 0; _i9 < _size7; ++_i9) {
          var elem10 = null;
          elem10 = new ttypes.Chat();
          elem10.read(input);
          this.chats.push(elem10);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetChatsResponse.prototype.write = function(output) {
  output.writeStructBegin('GetChatsResponse');
  if (this.chats !== null && this.chats !== undefined) {
    output.writeFieldBegin('chats', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRUCT, this.chats.length);
    for (var iter11 in this.chats) {
      if (this.chats.hasOwnProperty(iter11)) {
        iter11 = this.chats[iter11];
        iter11.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RejectChatInvitationResponse = module.exports.RejectChatInvitationResponse = function(args) {
};
RejectChatInvitationResponse.prototype = {};
RejectChatInvitationResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RejectChatInvitationResponse.prototype.write = function(output) {
  output.writeStructBegin('RejectChatInvitationResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UpdateChatResponse = module.exports.UpdateChatResponse = function(args) {
};
UpdateChatResponse.prototype = {};
UpdateChatResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UpdateChatResponse.prototype.write = function(output) {
  output.writeStructBegin('UpdateChatResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AcceptChatInvitationResponse = module.exports.AcceptChatInvitationResponse = function(args) {
};
AcceptChatInvitationResponse.prototype = {};
AcceptChatInvitationResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AcceptChatInvitationResponse.prototype.write = function(output) {
  output.writeStructBegin('AcceptChatInvitationResponse');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GetAllChatMidsResponse = module.exports.GetAllChatMidsResponse = function(args) {
  this.memberChatMids = null;
  this.invitedChatMids = null;
  if (args) {
    if (args.memberChatMids !== undefined && args.memberChatMids !== null) {
      this.memberChatMids = Thrift.copyList(args.memberChatMids, [null]);
    }
    if (args.invitedChatMids !== undefined && args.invitedChatMids !== null) {
      this.invitedChatMids = Thrift.copyList(args.invitedChatMids, [null]);
    }
  }
};
GetAllChatMidsResponse.prototype = {};
GetAllChatMidsResponse.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.SET) {
        this.memberChatMids = [];
        var _rtmp313 = input.readSetBegin();
        var _size12 = _rtmp313.size || 0;
        for (var _i14 = 0; _i14 < _size12; ++_i14) {
          var elem15 = null;
          elem15 = input.readString();
          this.memberChatMids.push(elem15);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.SET) {
        this.invitedChatMids = [];
        var _rtmp317 = input.readSetBegin();
        var _size16 = _rtmp317.size || 0;
        for (var _i18 = 0; _i18 < _size16; ++_i18) {
          var elem19 = null;
          elem19 = input.readString();
          this.invitedChatMids.push(elem19);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetAllChatMidsResponse.prototype.write = function(output) {
  output.writeStructBegin('GetAllChatMidsResponse');
  if (this.memberChatMids !== null && this.memberChatMids !== undefined) {
    output.writeFieldBegin('memberChatMids', Thrift.Type.SET, 1);
    output.writeSetBegin(Thrift.Type.STRING, this.memberChatMids.length);
    for (var iter20 in this.memberChatMids) {
      if (this.memberChatMids.hasOwnProperty(iter20)) {
        iter20 = this.memberChatMids[iter20];
        output.writeString(iter20);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  if (this.invitedChatMids !== null && this.invitedChatMids !== undefined) {
    output.writeFieldBegin('invitedChatMids', Thrift.Type.SET, 2);
    output.writeSetBegin(Thrift.Type.STRING, this.invitedChatMids.length);
    for (var iter21 in this.invitedChatMids) {
      if (this.invitedChatMids.hasOwnProperty(iter21)) {
        iter21 = this.invitedChatMids[iter21];
        output.writeString(iter21);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Chat = module.exports.Chat = function(args) {
  this.type = null;
  this.chatMid = null;
  this.createdTime = null;
  this.notificationDisabled = null;
  this.favoriteTimestamp = null;
  this.chatName = null;
  this.picturePath = null;
  this.extra = null;
  if (args) {
    if (args.type !== undefined && args.type !== null) {
      this.type = args.type;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
    if (args.createdTime !== undefined && args.createdTime !== null) {
      this.createdTime = args.createdTime;
    }
    if (args.notificationDisabled !== undefined && args.notificationDisabled !== null) {
      this.notificationDisabled = args.notificationDisabled;
    }
    if (args.favoriteTimestamp !== undefined && args.favoriteTimestamp !== null) {
      this.favoriteTimestamp = args.favoriteTimestamp;
    }
    if (args.chatName !== undefined && args.chatName !== null) {
      this.chatName = args.chatName;
    }
    if (args.picturePath !== undefined && args.picturePath !== null) {
      this.picturePath = args.picturePath;
    }
    if (args.extra !== undefined && args.extra !== null) {
      this.extra = new ttypes.Extra(args.extra);
    }
  }
};
Chat.prototype = {};
Chat.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.type = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.createdTime = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.BOOL) {
        this.notificationDisabled = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I64) {
        this.favoriteTimestamp = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRING) {
        this.chatName = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRING) {
        this.picturePath = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRUCT) {
        this.extra = new ttypes.Extra();
        this.extra.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Chat.prototype.write = function(output) {
  output.writeStructBegin('Chat');
  if (this.type !== null && this.type !== undefined) {
    output.writeFieldBegin('type', Thrift.Type.I32, 1);
    output.writeI32(this.type);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  if (this.createdTime !== null && this.createdTime !== undefined) {
    output.writeFieldBegin('createdTime', Thrift.Type.I64, 3);
    output.writeI64(this.createdTime);
    output.writeFieldEnd();
  }
  if (this.notificationDisabled !== null && this.notificationDisabled !== undefined) {
    output.writeFieldBegin('notificationDisabled', Thrift.Type.BOOL, 4);
    output.writeBool(this.notificationDisabled);
    output.writeFieldEnd();
  }
  if (this.favoriteTimestamp !== null && this.favoriteTimestamp !== undefined) {
    output.writeFieldBegin('favoriteTimestamp', Thrift.Type.I64, 5);
    output.writeI64(this.favoriteTimestamp);
    output.writeFieldEnd();
  }
  if (this.chatName !== null && this.chatName !== undefined) {
    output.writeFieldBegin('chatName', Thrift.Type.STRING, 6);
    output.writeString(this.chatName);
    output.writeFieldEnd();
  }
  if (this.picturePath !== null && this.picturePath !== undefined) {
    output.writeFieldBegin('picturePath', Thrift.Type.STRING, 7);
    output.writeString(this.picturePath);
    output.writeFieldEnd();
  }
  if (this.extra !== null && this.extra !== undefined) {
    output.writeFieldBegin('extra', Thrift.Type.STRUCT, 8);
    this.extra.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Extra = module.exports.Extra = function(args) {
  this.groupExtra = null;
  this.peerExtra = null;
  if (args) {
    if (args.groupExtra !== undefined && args.groupExtra !== null) {
      this.groupExtra = new ttypes.GroupExtra(args.groupExtra);
    }
    if (args.peerExtra !== undefined && args.peerExtra !== null) {
      this.peerExtra = new ttypes.PeerExtra(args.peerExtra);
    }
  }
};
Extra.prototype = {};
Extra.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.groupExtra = new ttypes.GroupExtra();
        this.groupExtra.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.peerExtra = new ttypes.PeerExtra();
        this.peerExtra.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Extra.prototype.write = function(output) {
  output.writeStructBegin('Extra');
  if (this.groupExtra !== null && this.groupExtra !== undefined) {
    output.writeFieldBegin('groupExtra', Thrift.Type.STRUCT, 1);
    this.groupExtra.write(output);
    output.writeFieldEnd();
  }
  if (this.peerExtra !== null && this.peerExtra !== undefined) {
    output.writeFieldBegin('peerExtra', Thrift.Type.STRUCT, 2);
    this.peerExtra.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ExtendedProfile = module.exports.ExtendedProfile = function(args) {
  this.birthday = null;
  if (args) {
    if (args.birthday !== undefined && args.birthday !== null) {
      this.birthday = new ttypes.ExtendedProfileBirthday(args.birthday);
    }
  }
};
ExtendedProfile.prototype = {};
ExtendedProfile.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.birthday = new ttypes.ExtendedProfileBirthday();
        this.birthday.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ExtendedProfile.prototype.write = function(output) {
  output.writeStructBegin('ExtendedProfile');
  if (this.birthday !== null && this.birthday !== undefined) {
    output.writeFieldBegin('birthday', Thrift.Type.STRUCT, 1);
    this.birthday.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ExtendedProfileBirthday = module.exports.ExtendedProfileBirthday = function(args) {
  this.year = null;
  this.yearPrivacyLevelType = null;
  this.yearEnabled = null;
  this.day = null;
  this.dayPrivacyLevelType = null;
  this.dayEnabled = null;
  if (args) {
    if (args.year !== undefined && args.year !== null) {
      this.year = args.year;
    }
    if (args.yearPrivacyLevelType !== undefined && args.yearPrivacyLevelType !== null) {
      this.yearPrivacyLevelType = args.yearPrivacyLevelType;
    }
    if (args.yearEnabled !== undefined && args.yearEnabled !== null) {
      this.yearEnabled = args.yearEnabled;
    }
    if (args.day !== undefined && args.day !== null) {
      this.day = args.day;
    }
    if (args.dayPrivacyLevelType !== undefined && args.dayPrivacyLevelType !== null) {
      this.dayPrivacyLevelType = args.dayPrivacyLevelType;
    }
    if (args.dayEnabled !== undefined && args.dayEnabled !== null) {
      this.dayEnabled = args.dayEnabled;
    }
  }
};
ExtendedProfileBirthday.prototype = {};
ExtendedProfileBirthday.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.year = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.yearPrivacyLevelType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.yearEnabled = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.day = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I32) {
        this.dayPrivacyLevelType = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.BOOL) {
        this.dayEnabled = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ExtendedProfileBirthday.prototype.write = function(output) {
  output.writeStructBegin('ExtendedProfileBirthday');
  if (this.year !== null && this.year !== undefined) {
    output.writeFieldBegin('year', Thrift.Type.STRING, 1);
    output.writeString(this.year);
    output.writeFieldEnd();
  }
  if (this.yearPrivacyLevelType !== null && this.yearPrivacyLevelType !== undefined) {
    output.writeFieldBegin('yearPrivacyLevelType', Thrift.Type.I32, 2);
    output.writeI32(this.yearPrivacyLevelType);
    output.writeFieldEnd();
  }
  if (this.yearEnabled !== null && this.yearEnabled !== undefined) {
    output.writeFieldBegin('yearEnabled', Thrift.Type.BOOL, 3);
    output.writeBool(this.yearEnabled);
    output.writeFieldEnd();
  }
  if (this.day !== null && this.day !== undefined) {
    output.writeFieldBegin('day', Thrift.Type.STRING, 5);
    output.writeString(this.day);
    output.writeFieldEnd();
  }
  if (this.dayPrivacyLevelType !== null && this.dayPrivacyLevelType !== undefined) {
    output.writeFieldBegin('dayPrivacyLevelType', Thrift.Type.I32, 6);
    output.writeI32(this.dayPrivacyLevelType);
    output.writeFieldEnd();
  }
  if (this.dayEnabled !== null && this.dayEnabled !== undefined) {
    output.writeFieldBegin('dayEnabled', Thrift.Type.BOOL, 7);
    output.writeBool(this.dayEnabled);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GroupExtra = module.exports.GroupExtra = function(args) {
  this.creator = null;
  this.preventedJoinByTicket = null;
  this.invitationTicket = null;
  this.memberMids = null;
  this.inviteeMids = null;
  if (args) {
    if (args.creator !== undefined && args.creator !== null) {
      this.creator = args.creator;
    }
    if (args.preventedJoinByTicket !== undefined && args.preventedJoinByTicket !== null) {
      this.preventedJoinByTicket = args.preventedJoinByTicket;
    }
    if (args.invitationTicket !== undefined && args.invitationTicket !== null) {
      this.invitationTicket = args.invitationTicket;
    }
    if (args.memberMids !== undefined && args.memberMids !== null) {
      this.memberMids = Thrift.copyMap(args.memberMids, [null]);
    }
    if (args.inviteeMids !== undefined && args.inviteeMids !== null) {
      this.inviteeMids = Thrift.copyMap(args.inviteeMids, [null]);
    }
  }
};
GroupExtra.prototype = {};
GroupExtra.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.creator = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BOOL) {
        this.preventedJoinByTicket = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.invitationTicket = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.MAP) {
        this.memberMids = {};
        var _rtmp323 = input.readMapBegin();
        var _size22 = _rtmp323.size || 0;
        for (var _i24 = 0; _i24 < _size22; ++_i24) {
          var key25 = null;
          var val26 = null;
          key25 = input.readString();
          val26 = input.readI64();
          this.memberMids[key25] = val26;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.MAP) {
        this.inviteeMids = {};
        var _rtmp328 = input.readMapBegin();
        var _size27 = _rtmp328.size || 0;
        for (var _i29 = 0; _i29 < _size27; ++_i29) {
          var key30 = null;
          var val31 = null;
          key30 = input.readString();
          val31 = input.readI64();
          this.inviteeMids[key30] = val31;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GroupExtra.prototype.write = function(output) {
  output.writeStructBegin('GroupExtra');
  if (this.creator !== null && this.creator !== undefined) {
    output.writeFieldBegin('creator', Thrift.Type.STRING, 1);
    output.writeString(this.creator);
    output.writeFieldEnd();
  }
  if (this.preventedJoinByTicket !== null && this.preventedJoinByTicket !== undefined) {
    output.writeFieldBegin('preventedJoinByTicket', Thrift.Type.BOOL, 2);
    output.writeBool(this.preventedJoinByTicket);
    output.writeFieldEnd();
  }
  if (this.invitationTicket !== null && this.invitationTicket !== undefined) {
    output.writeFieldBegin('invitationTicket', Thrift.Type.STRING, 3);
    output.writeString(this.invitationTicket);
    output.writeFieldEnd();
  }
  if (this.memberMids !== null && this.memberMids !== undefined) {
    output.writeFieldBegin('memberMids', Thrift.Type.MAP, 4);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.I64, Thrift.objectLength(this.memberMids));
    for (var kiter32 in this.memberMids) {
      if (this.memberMids.hasOwnProperty(kiter32)) {
        var viter33 = this.memberMids[kiter32];
        output.writeString(kiter32);
        output.writeI64(viter33);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.inviteeMids !== null && this.inviteeMids !== undefined) {
    output.writeFieldBegin('inviteeMids', Thrift.Type.MAP, 5);
    output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.I64, Thrift.objectLength(this.inviteeMids));
    for (var kiter34 in this.inviteeMids) {
      if (this.inviteeMids.hasOwnProperty(kiter34)) {
        var viter35 = this.inviteeMids[kiter34];
        output.writeString(kiter34);
        output.writeI64(viter35);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PeerExtra = module.exports.PeerExtra = function(args) {
};
PeerExtra.prototype = {};
PeerExtra.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PeerExtra.prototype.write = function(output) {
  output.writeStructBegin('PeerExtra');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Category = module.exports.Category = function(args) {
  this.id = null;
  this.name = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.name !== undefined && args.name !== null) {
      this.name = args.name;
    }
  }
};
Category.prototype = {};
Category.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.name = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Category.prototype.write = function(output) {
  output.writeStructBegin('Category');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.I32, 2);
    output.writeI32(this.name);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ChatEffectMetaContent = module.exports.ChatEffectMetaContent = function(args) {
  this.url = null;
  this.checksum = null;
  if (args) {
    if (args.url !== undefined && args.url !== null) {
      this.url = args.url;
    }
    if (args.checksum !== undefined && args.checksum !== null) {
      this.checksum = args.checksum;
    }
  }
};
ChatEffectMetaContent.prototype = {};
ChatEffectMetaContent.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.url = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.checksum = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ChatEffectMetaContent.prototype.write = function(output) {
  output.writeStructBegin('ChatEffectMetaContent');
  if (this.url !== null && this.url !== undefined) {
    output.writeFieldBegin('url', Thrift.Type.STRING, 1);
    output.writeString(this.url);
    output.writeFieldEnd();
  }
  if (this.checksum !== null && this.checksum !== undefined) {
    output.writeFieldBegin('checksum', Thrift.Type.STRING, 2);
    output.writeString(this.checksum);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ChatEffectMeta = module.exports.ChatEffectMeta = function(args) {
  this.contentId = null;
  this.category = null;
  this.name = null;
  this.defaultContent = null;
  this.optionalContents = null;
  this.keywords = null;
  this.beginTimeMillis = null;
  this.endTimeMillis = null;
  this.createdTimeMillis = null;
  this.updatedTimeMillis = null;
  if (args) {
    if (args.contentId !== undefined && args.contentId !== null) {
      this.contentId = args.contentId;
    }
    if (args.category !== undefined && args.category !== null) {
      this.category = new ttypes.Category(args.category);
    }
    if (args.name !== undefined && args.name !== null) {
      this.name = args.name;
    }
    if (args.defaultContent !== undefined && args.defaultContent !== null) {
      this.defaultContent = new ttypes.ChatEffectMetaContent(args.defaultContent);
    }
    if (args.optionalContents !== undefined && args.optionalContents !== null) {
      this.optionalContents = Thrift.copyMap(args.optionalContents, [ttypes.ChatEffectMetaContent]);
    }
    if (args.keywords !== undefined && args.keywords !== null) {
      this.keywords = Thrift.copyList(args.keywords, [null]);
    }
    if (args.beginTimeMillis !== undefined && args.beginTimeMillis !== null) {
      this.beginTimeMillis = args.beginTimeMillis;
    }
    if (args.endTimeMillis !== undefined && args.endTimeMillis !== null) {
      this.endTimeMillis = args.endTimeMillis;
    }
    if (args.createdTimeMillis !== undefined && args.createdTimeMillis !== null) {
      this.createdTimeMillis = args.createdTimeMillis;
    }
    if (args.updatedTimeMillis !== undefined && args.updatedTimeMillis !== null) {
      this.updatedTimeMillis = args.updatedTimeMillis;
    }
  }
};
ChatEffectMeta.prototype = {};
ChatEffectMeta.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.contentId = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.category = new ttypes.Category();
        this.category.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.name = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRUCT) {
        this.defaultContent = new ttypes.ChatEffectMetaContent();
        this.defaultContent.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.MAP) {
        this.optionalContents = {};
        var _rtmp337 = input.readMapBegin();
        var _size36 = _rtmp337.size || 0;
        for (var _i38 = 0; _i38 < _size36; ++_i38) {
          var key39 = null;
          var val40 = null;
          key39 = input.readI32();
          val40 = new ttypes.ChatEffectMetaContent();
          val40.read(input);
          this.optionalContents[key39] = val40;
        }
        input.readMapEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.SET) {
        this.keywords = [];
        var _rtmp342 = input.readSetBegin();
        var _size41 = _rtmp342.size || 0;
        for (var _i43 = 0; _i43 < _size41; ++_i43) {
          var elem44 = null;
          elem44 = input.readString();
          this.keywords.push(elem44);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.I64) {
        this.beginTimeMillis = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.I64) {
        this.endTimeMillis = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.I64) {
        this.createdTimeMillis = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.I64) {
        this.updatedTimeMillis = input.readI64();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ChatEffectMeta.prototype.write = function(output) {
  output.writeStructBegin('ChatEffectMeta');
  if (this.contentId !== null && this.contentId !== undefined) {
    output.writeFieldBegin('contentId', Thrift.Type.I64, 1);
    output.writeI64(this.contentId);
    output.writeFieldEnd();
  }
  if (this.category !== null && this.category !== undefined) {
    output.writeFieldBegin('category', Thrift.Type.STRUCT, 2);
    this.category.write(output);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.I32, 3);
    output.writeI32(this.name);
    output.writeFieldEnd();
  }
  if (this.defaultContent !== null && this.defaultContent !== undefined) {
    output.writeFieldBegin('defaultContent', Thrift.Type.STRUCT, 4);
    this.defaultContent.write(output);
    output.writeFieldEnd();
  }
  if (this.optionalContents !== null && this.optionalContents !== undefined) {
    output.writeFieldBegin('optionalContents', Thrift.Type.MAP, 5);
    output.writeMapBegin(Thrift.Type.I32, Thrift.Type.STRUCT, Thrift.objectLength(this.optionalContents));
    for (var kiter45 in this.optionalContents) {
      if (this.optionalContents.hasOwnProperty(kiter45)) {
        var viter46 = this.optionalContents[kiter45];
        output.writeI32(kiter45);
        viter46.write(output);
      }
    }
    output.writeMapEnd();
    output.writeFieldEnd();
  }
  if (this.keywords !== null && this.keywords !== undefined) {
    output.writeFieldBegin('keywords', Thrift.Type.SET, 6);
    output.writeSetBegin(Thrift.Type.STRING, this.keywords.length);
    for (var iter47 in this.keywords) {
      if (this.keywords.hasOwnProperty(iter47)) {
        iter47 = this.keywords[iter47];
        output.writeString(iter47);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  if (this.beginTimeMillis !== null && this.beginTimeMillis !== undefined) {
    output.writeFieldBegin('beginTimeMillis', Thrift.Type.I64, 7);
    output.writeI64(this.beginTimeMillis);
    output.writeFieldEnd();
  }
  if (this.endTimeMillis !== null && this.endTimeMillis !== undefined) {
    output.writeFieldBegin('endTimeMillis', Thrift.Type.I64, 8);
    output.writeI64(this.endTimeMillis);
    output.writeFieldEnd();
  }
  if (this.createdTimeMillis !== null && this.createdTimeMillis !== undefined) {
    output.writeFieldBegin('createdTimeMillis', Thrift.Type.I64, 9);
    output.writeI64(this.createdTimeMillis);
    output.writeFieldEnd();
  }
  if (this.updatedTimeMillis !== null && this.updatedTimeMillis !== undefined) {
    output.writeFieldBegin('updatedTimeMillis', Thrift.Type.I64, 10);
    output.writeI64(this.updatedTimeMillis);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AcceptChatInvitationByTicketRequest = module.exports.AcceptChatInvitationByTicketRequest = function(args) {
  this.reqSeq = null;
  this.chatMid = null;
  this.ticketId = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
    if (args.ticketId !== undefined && args.ticketId !== null) {
      this.ticketId = args.ticketId;
    }
  }
};
AcceptChatInvitationByTicketRequest.prototype = {};
AcceptChatInvitationByTicketRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.ticketId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AcceptChatInvitationByTicketRequest.prototype.write = function(output) {
  output.writeStructBegin('AcceptChatInvitationByTicketRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  if (this.ticketId !== null && this.ticketId !== undefined) {
    output.writeFieldBegin('ticketId', Thrift.Type.STRING, 3);
    output.writeString(this.ticketId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CancelChatInvitationRequest = module.exports.CancelChatInvitationRequest = function(args) {
  this.reqSeq = null;
  this.chatMid = null;
  this.targetUserMids = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
    if (args.targetUserMids !== undefined && args.targetUserMids !== null) {
      this.targetUserMids = Thrift.copyList(args.targetUserMids, [null]);
    }
  }
};
CancelChatInvitationRequest.prototype = {};
CancelChatInvitationRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.SET) {
        this.targetUserMids = [];
        var _rtmp349 = input.readSetBegin();
        var _size48 = _rtmp349.size || 0;
        for (var _i50 = 0; _i50 < _size48; ++_i50) {
          var elem51 = null;
          elem51 = input.readString();
          this.targetUserMids.push(elem51);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CancelChatInvitationRequest.prototype.write = function(output) {
  output.writeStructBegin('CancelChatInvitationRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  if (this.targetUserMids !== null && this.targetUserMids !== undefined) {
    output.writeFieldBegin('targetUserMids', Thrift.Type.SET, 3);
    output.writeSetBegin(Thrift.Type.STRING, this.targetUserMids.length);
    for (var iter52 in this.targetUserMids) {
      if (this.targetUserMids.hasOwnProperty(iter52)) {
        iter52 = this.targetUserMids[iter52];
        output.writeString(iter52);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var CreateChatRequest = module.exports.CreateChatRequest = function(args) {
  this.reqSeq = null;
  this.type = null;
  this.name = null;
  this.targetUserMids = null;
  this.picturePath = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.type !== undefined && args.type !== null) {
      this.type = args.type;
    }
    if (args.name !== undefined && args.name !== null) {
      this.name = args.name;
    }
    if (args.targetUserMids !== undefined && args.targetUserMids !== null) {
      this.targetUserMids = Thrift.copyList(args.targetUserMids, [null]);
    }
    if (args.picturePath !== undefined && args.picturePath !== null) {
      this.picturePath = args.picturePath;
    }
  }
};
CreateChatRequest.prototype = {};
CreateChatRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.type = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.SET) {
        this.targetUserMids = [];
        var _rtmp354 = input.readSetBegin();
        var _size53 = _rtmp354.size || 0;
        for (var _i55 = 0; _i55 < _size53; ++_i55) {
          var elem56 = null;
          elem56 = input.readString();
          this.targetUserMids.push(elem56);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.picturePath = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

CreateChatRequest.prototype.write = function(output) {
  output.writeStructBegin('CreateChatRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.type !== null && this.type !== undefined) {
    output.writeFieldBegin('type', Thrift.Type.I32, 2);
    output.writeI32(this.type);
    output.writeFieldEnd();
  }
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 3);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.targetUserMids !== null && this.targetUserMids !== undefined) {
    output.writeFieldBegin('targetUserMids', Thrift.Type.SET, 4);
    output.writeSetBegin(Thrift.Type.STRING, this.targetUserMids.length);
    for (var iter57 in this.targetUserMids) {
      if (this.targetUserMids.hasOwnProperty(iter57)) {
        iter57 = this.targetUserMids[iter57];
        output.writeString(iter57);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  if (this.picturePath !== null && this.picturePath !== undefined) {
    output.writeFieldBegin('picturePath', Thrift.Type.STRING, 5);
    output.writeString(this.picturePath);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DeleteOtherFromChatRequest = module.exports.DeleteOtherFromChatRequest = function(args) {
  this.reqSeq = null;
  this.chatMid = null;
  this.targetUserMids = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
    if (args.targetUserMids !== undefined && args.targetUserMids !== null) {
      this.targetUserMids = Thrift.copyList(args.targetUserMids, [null]);
    }
  }
};
DeleteOtherFromChatRequest.prototype = {};
DeleteOtherFromChatRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.SET) {
        this.targetUserMids = [];
        var _rtmp359 = input.readSetBegin();
        var _size58 = _rtmp359.size || 0;
        for (var _i60 = 0; _i60 < _size58; ++_i60) {
          var elem61 = null;
          elem61 = input.readString();
          this.targetUserMids.push(elem61);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DeleteOtherFromChatRequest.prototype.write = function(output) {
  output.writeStructBegin('DeleteOtherFromChatRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  if (this.targetUserMids !== null && this.targetUserMids !== undefined) {
    output.writeFieldBegin('targetUserMids', Thrift.Type.SET, 3);
    output.writeSetBegin(Thrift.Type.STRING, this.targetUserMids.length);
    for (var iter62 in this.targetUserMids) {
      if (this.targetUserMids.hasOwnProperty(iter62)) {
        iter62 = this.targetUserMids[iter62];
        output.writeString(iter62);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DeleteSelfFromChatRequest = module.exports.DeleteSelfFromChatRequest = function(args) {
  this.reqSeq = null;
  this.chatMid = null;
  this.lastSeenMessageDeliveredTime = null;
  this.lastSeenMessageId = null;
  this.lastMessageDeliveredTime = null;
  this.lastMessageId = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
    if (args.lastSeenMessageDeliveredTime !== undefined && args.lastSeenMessageDeliveredTime !== null) {
      this.lastSeenMessageDeliveredTime = args.lastSeenMessageDeliveredTime;
    }
    if (args.lastSeenMessageId !== undefined && args.lastSeenMessageId !== null) {
      this.lastSeenMessageId = args.lastSeenMessageId;
    }
    if (args.lastMessageDeliveredTime !== undefined && args.lastMessageDeliveredTime !== null) {
      this.lastMessageDeliveredTime = args.lastMessageDeliveredTime;
    }
    if (args.lastMessageId !== undefined && args.lastMessageId !== null) {
      this.lastMessageId = args.lastMessageId;
    }
  }
};
DeleteSelfFromChatRequest.prototype = {};
DeleteSelfFromChatRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.lastSeenMessageDeliveredTime = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.lastSeenMessageId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.lastMessageDeliveredTime = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRING) {
        this.lastMessageId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DeleteSelfFromChatRequest.prototype.write = function(output) {
  output.writeStructBegin('DeleteSelfFromChatRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  if (this.lastSeenMessageDeliveredTime !== null && this.lastSeenMessageDeliveredTime !== undefined) {
    output.writeFieldBegin('lastSeenMessageDeliveredTime', Thrift.Type.I32, 3);
    output.writeI32(this.lastSeenMessageDeliveredTime);
    output.writeFieldEnd();
  }
  if (this.lastSeenMessageId !== null && this.lastSeenMessageId !== undefined) {
    output.writeFieldBegin('lastSeenMessageId', Thrift.Type.STRING, 4);
    output.writeString(this.lastSeenMessageId);
    output.writeFieldEnd();
  }
  if (this.lastMessageDeliveredTime !== null && this.lastMessageDeliveredTime !== undefined) {
    output.writeFieldBegin('lastMessageDeliveredTime', Thrift.Type.I32, 5);
    output.writeI32(this.lastMessageDeliveredTime);
    output.writeFieldEnd();
  }
  if (this.lastMessageId !== null && this.lastMessageId !== undefined) {
    output.writeFieldBegin('lastMessageId', Thrift.Type.STRING, 6);
    output.writeString(this.lastMessageId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var FindChatByTicketRequest = module.exports.FindChatByTicketRequest = function(args) {
  this.ticketId = null;
  if (args) {
    if (args.ticketId !== undefined && args.ticketId !== null) {
      this.ticketId = args.ticketId;
    }
  }
};
FindChatByTicketRequest.prototype = {};
FindChatByTicketRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.ticketId = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

FindChatByTicketRequest.prototype.write = function(output) {
  output.writeStructBegin('FindChatByTicketRequest');
  if (this.ticketId !== null && this.ticketId !== undefined) {
    output.writeFieldBegin('ticketId', Thrift.Type.STRING, 1);
    output.writeString(this.ticketId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GetAllChatMidsRequest = module.exports.GetAllChatMidsRequest = function(args) {
  this.withMemberChats = null;
  this.withInvitedChats = null;
  if (args) {
    if (args.withMemberChats !== undefined && args.withMemberChats !== null) {
      this.withMemberChats = args.withMemberChats;
    }
    if (args.withInvitedChats !== undefined && args.withInvitedChats !== null) {
      this.withInvitedChats = args.withInvitedChats;
    }
  }
};
GetAllChatMidsRequest.prototype = {};
GetAllChatMidsRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.withMemberChats = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BOOL) {
        this.withInvitedChats = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetAllChatMidsRequest.prototype.write = function(output) {
  output.writeStructBegin('GetAllChatMidsRequest');
  if (this.withMemberChats !== null && this.withMemberChats !== undefined) {
    output.writeFieldBegin('withMemberChats', Thrift.Type.BOOL, 1);
    output.writeBool(this.withMemberChats);
    output.writeFieldEnd();
  }
  if (this.withInvitedChats !== null && this.withInvitedChats !== undefined) {
    output.writeFieldBegin('withInvitedChats', Thrift.Type.BOOL, 2);
    output.writeBool(this.withInvitedChats);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var InviteIntoChatRequest = module.exports.InviteIntoChatRequest = function(args) {
  this.reqSeq = null;
  this.chatMid = null;
  this.targetUserMids = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
    if (args.targetUserMids !== undefined && args.targetUserMids !== null) {
      this.targetUserMids = Thrift.copyList(args.targetUserMids, [null]);
    }
  }
};
InviteIntoChatRequest.prototype = {};
InviteIntoChatRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.SET) {
        this.targetUserMids = [];
        var _rtmp364 = input.readSetBegin();
        var _size63 = _rtmp364.size || 0;
        for (var _i65 = 0; _i65 < _size63; ++_i65) {
          var elem66 = null;
          elem66 = input.readString();
          this.targetUserMids.push(elem66);
        }
        input.readSetEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

InviteIntoChatRequest.prototype.write = function(output) {
  output.writeStructBegin('InviteIntoChatRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  if (this.targetUserMids !== null && this.targetUserMids !== undefined) {
    output.writeFieldBegin('targetUserMids', Thrift.Type.SET, 3);
    output.writeSetBegin(Thrift.Type.STRING, this.targetUserMids.length);
    for (var iter67 in this.targetUserMids) {
      if (this.targetUserMids.hasOwnProperty(iter67)) {
        iter67 = this.targetUserMids[iter67];
        output.writeString(iter67);
      }
    }
    output.writeSetEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ReissueChatTicketRequest = module.exports.ReissueChatTicketRequest = function(args) {
  this.reqSeq = null;
  this.chatMid = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
  }
};
ReissueChatTicketRequest.prototype = {};
ReissueChatTicketRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ReissueChatTicketRequest.prototype.write = function(output) {
  output.writeStructBegin('ReissueChatTicketRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GetChatsRequest = module.exports.GetChatsRequest = function(args) {
  this.chatMids = null;
  this.withMembers = null;
  this.withInvitees = null;
  if (args) {
    if (args.chatMids !== undefined && args.chatMids !== null) {
      this.chatMids = Thrift.copyList(args.chatMids, [null]);
    }
    if (args.withMembers !== undefined && args.withMembers !== null) {
      this.withMembers = args.withMembers;
    }
    if (args.withInvitees !== undefined && args.withInvitees !== null) {
      this.withInvitees = args.withInvitees;
    }
  }
};
GetChatsRequest.prototype = {};
GetChatsRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.LIST) {
        this.chatMids = [];
        var _rtmp369 = input.readListBegin();
        var _size68 = _rtmp369.size || 0;
        for (var _i70 = 0; _i70 < _size68; ++_i70) {
          var elem71 = null;
          elem71 = input.readString();
          this.chatMids.push(elem71);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BOOL) {
        this.withMembers = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BOOL) {
        this.withInvitees = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GetChatsRequest.prototype.write = function(output) {
  output.writeStructBegin('GetChatsRequest');
  if (this.chatMids !== null && this.chatMids !== undefined) {
    output.writeFieldBegin('chatMids', Thrift.Type.LIST, 1);
    output.writeListBegin(Thrift.Type.STRING, this.chatMids.length);
    for (var iter72 in this.chatMids) {
      if (this.chatMids.hasOwnProperty(iter72)) {
        iter72 = this.chatMids[iter72];
        output.writeString(iter72);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.withMembers !== null && this.withMembers !== undefined) {
    output.writeFieldBegin('withMembers', Thrift.Type.BOOL, 2);
    output.writeBool(this.withMembers);
    output.writeFieldEnd();
  }
  if (this.withInvitees !== null && this.withInvitees !== undefined) {
    output.writeFieldBegin('withInvitees', Thrift.Type.BOOL, 3);
    output.writeBool(this.withInvitees);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RejectChatInvitationRequest = module.exports.RejectChatInvitationRequest = function(args) {
  this.reqSeq = null;
  this.chatMid = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
  }
};
RejectChatInvitationRequest.prototype = {};
RejectChatInvitationRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RejectChatInvitationRequest.prototype.write = function(output) {
  output.writeStructBegin('RejectChatInvitationRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var UpdateChatRequest = module.exports.UpdateChatRequest = function(args) {
  this.reqSeq = null;
  this.chat = null;
  this.updatedAttribute = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chat !== undefined && args.chat !== null) {
      this.chat = new ttypes.Chat(args.chat);
    }
    if (args.updatedAttribute !== undefined && args.updatedAttribute !== null) {
      this.updatedAttribute = args.updatedAttribute;
    }
  }
};
UpdateChatRequest.prototype = {};
UpdateChatRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.chat = new ttypes.Chat();
        this.chat.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.updatedAttribute = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

UpdateChatRequest.prototype.write = function(output) {
  output.writeStructBegin('UpdateChatRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chat !== null && this.chat !== undefined) {
    output.writeFieldBegin('chat', Thrift.Type.STRUCT, 2);
    this.chat.write(output);
    output.writeFieldEnd();
  }
  if (this.updatedAttribute !== null && this.updatedAttribute !== undefined) {
    output.writeFieldBegin('updatedAttribute', Thrift.Type.I32, 3);
    output.writeI32(this.updatedAttribute);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var AcceptChatInvitationRequest = module.exports.AcceptChatInvitationRequest = function(args) {
  this.reqSeq = null;
  this.chatMid = null;
  if (args) {
    if (args.reqSeq !== undefined && args.reqSeq !== null) {
      this.reqSeq = args.reqSeq;
    }
    if (args.chatMid !== undefined && args.chatMid !== null) {
      this.chatMid = args.chatMid;
    }
  }
};
AcceptChatInvitationRequest.prototype = {};
AcceptChatInvitationRequest.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.reqSeq = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.chatMid = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AcceptChatInvitationRequest.prototype.write = function(output) {
  output.writeStructBegin('AcceptChatInvitationRequest');
  if (this.reqSeq !== null && this.reqSeq !== undefined) {
    output.writeFieldBegin('reqSeq', Thrift.Type.I32, 1);
    output.writeI32(this.reqSeq);
    output.writeFieldEnd();
  }
  if (this.chatMid !== null && this.chatMid !== undefined) {
    output.writeFieldBegin('chatMid', Thrift.Type.STRING, 2);
    output.writeString(this.chatMid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};